fragment BookmarkItem on Bookmarks {
  id
  link
  faviconUrl
  displayName
  position
}

fragment TraefikRoutes on TraefikRoutes {
  faviconUrl
  lastSeenAlive
  isUp
  name
  friendlyName
  faviconUrl
  link: calculatedUrl
}

query getListOfBookmarks {
  bookmarks(orderBy: { position: ASC_NULLS_LAST }) {
    ...BookmarkItem
  }

  traefikRoutes(
    orderBy: { createdAt: DESC }
    where: { isSown: { _eq: true } }
  ) {
    ...TraefikRoutes
  }
}

mutation InsertBookmark($object: BookmarksInsertInput!) {
  insertBookmarksOne(
    object: $object
    onConflict: { constraint: bookmarks_pkey, updateColumns: displayName }
  ) {
    position
    link
    id
    faviconUrl
    displayName
    userId
  }
}

mutation DeleteBookmarkById($id: uuid!) {
  deleteBookmarksByPk(id: $id) {
    id
  }
}
