version: '3.6'

services:
  postgres:
    image: postgres:12
    restart: on-failure
    container_name: dash-hasura-graphql-engine-postgres
    volumes:
      - db_dash-hasura:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v2.15.2
    ports:
      - '${HASURA_PORT}:8080'
    depends_on:
      - 'postgres'
    restart: on-failure
    container_name: dash-hasura-graphql-engine
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'false' # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: 'true'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_JWT_SECRET: '{ "jwk_url": "${HASURA_BACKEND_BASE_URL}/api/auth/jwt/jwks.json" }'
      HASURA_GRAPHQL_ADMIN_SECRET: '${HASURA_GRAPHQL_ADMIN_SECRET}'
      HASURA_GRAPHQL_EXPERIMENTAL_FEATURES: 'naming_convention'
      HASURA_BACKEND_BASE_URL: '${HASURA_BACKEND_BASE_URL}'
      HASURA_AUTH_TOKEN_CRON: '${HASURA_AUTH_TOKEN_CRON}'

volumes:
  db_dash-hasura: {}
