-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."traefikRoutes" add column "isSown" boolean
--  not null default 'TRUE';
