export const supportedAceLang = [
  'javascript',
  'java',
  'xml',
  'yaml',
  'typescript',
  'css',
  'sass',
  'json',
  'html',
  'kotlin',
  'text',
  'sh',
  'dockerfile',
  // 'java',
  // 'python',
  //  'ruby',
  //  'sass',
  //  'markdown',
  //  'mysql',
  //  'handlebars',
  //  'golang',
  //  'csharp',
  //  'elixir',
] as const;
export type SupportedLanguages = typeof supportedAceLang;
