version: '3.6'

name: courso-hasura

services:
  postgres:
    image: postgres:12
    restart: unless-stopped
    container_name: courso-hasura-graphql-engine-postgres
    volumes:
      - db_courso-hasura:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v2.32.1
    ports:
      - '${HASURA_PORT}:8080'
    depends_on:
      - 'postgres'
    restart: unless-stopped
    container_name: courso-hasura-graphql-engine
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'false' # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: 'true'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: '${HASURA_GRAPHQL_ADMIN_SECRET}'
      WEBHOOK_MASTER_URL: '${HASURA_WEBHOOK_MASTER_URL}'
      WEBHOOK_MASTER_TOKEN: '${HASURA_WEBHOOK_MASTER_TOKEN}'
      ACTION_MASTER_URL: '${HASURA_ACTION_MASTER_URL}'
      ACTION_MASTER_TOKEN: '${HASURA_ACTION_MASTER_TOKEN}'
      HASURA_GRAPHQL_EXPERIMENTAL_FEATURES: 'naming_convention'

volumes:
  db_courso-hasura: {}
