name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.13
    secrets:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    with:
      main-branch-name: main
      number-of-agents: 3
      install-commands: |
        sudo timedatectl set-timezone Europe/Paris
        yarn install --frozen-lockfile
      #init-commands: |
      #  yarn nx-cloud start-ci-run --stop-agents-after="test-storybook" --agent-count=3
      init-commands: |
        yarn nx-cloud start-ci-run --stop-agents-after="build" --agent-count=3
      parallel-commands: |
        yarn nx-cloud record -- yarn nx format:check
        yarn nx-cloud record -- yarn nx run nx-plugins-internal-generator:workspace-lint
      parallel-commands-on-agents: |
        yarn nx affected --target=build --parallel=4
        yarn nx affected --target=lint --parallel=5
        yarn nx affected --target=test --parallel=4 --ci --code-coverage
        yarn nx affected --target=e2e --parallel=1
# yarn nx affected -target=test-storybook --configuration ci --parallel=1

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.13
    secrets:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    with:
      install-commands: |
        sudo timedatectl set-timezone Europe/Paris
        yarn install --frozen-lockfile
      number-of-agents: 3
